In [40]:
# %pip install --force-reinstall "numpy==1.26.4" "pandas>=2.1,<3"

In [41]:
import pandas as pd
import numpy as np

# Pulling the separate data

In [42]:
import os 

print(os.getcwd())
os.chdir("../data/")
print(os.getcwd())


print("\nData to be curated:")
os.listdir()

/Users/caden/Desktop/psalms-text-comparison/data
/Users/caden/Desktop/psalms-text-comparison/data

Data to be curated:

['psalms_with_sentiment.csv',
 'cleaned_psalm_verses.csv',
 'psalms_with_data_2.csv',
 'psalms_with_data.csv',
 'grouped_psalm.csv',
 'psalms_with_bertTopic.csv']

---
## Sentiment Data

In [43]:
psalmSentiment = pd.read_csv("../data/psalms_with_sentiment.csv")
psalmSentiment.head()

,Unnamed: 0.1,Unnamed: 0,tradition,text,psalm_num,verse,cleaned_verse,vader_score,neg,neu,pos,compound,vader_category,polarity,subjectivity,emotional_score
0,0,0,Orthodox,Bible,1,Blessed is the man Who walks not in the counse...,blessed man walk counsel ungodly stand way sin...,"{'neg': 0.015, 'neu': 0.92, 'pos': 0.064, 'com...",0.015,0.920,0.064,0.7783,Positive,0.000000,0.000000,0.000000
1,1,1,Orthodox,Bible,2,Why do the nations rage And the people meditat...,nation rage people meditate vain thing king ea...,"{'neg': 0.12, 'neu': 0.787, 'pos': 0.093, 'com...",0.120,0.787,0.093,-0.6486,Negative,-0.153333,0.400000,-0.061333
2,2,2,Orthodox,Bible,3,A psalm by David when he fled from the face of...,psalm david fled face son absalom olord afflic...,"{'neg': 0.089, 'neu': 0.786, 'pos': 0.126, 'co...",0.089,0.786,0.126,0.8020,Positive,0.048889,0.437778,0.021402
3,3,3,Orthodox,Bible,4,For the End in psalms an ode by David You hear...,end psalm ode david heard icalled god righteou...,"{'neg': 0.092, 'neu': 0.748, 'pos': 0.159, 'co...",0.092,0.748,0.159,0.8919,Positive,0.178571,0.600000,0.107143
4,4,4,Orthodox,Bible,5,For the End concerning the inheritance a psalm...,end concerning inheritance psalm david give ea...,"{'neg': 0.13, 'neu': 0.712, 'pos': 0.157, 'com...",0.130,0.712,0.157,0.7774,Positive,0.075000,0.593750,0.044531

In [44]:
psalmSentiment.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'tradition', 'text', 'psalm_num', 'verse',
       'cleaned_verse', 'vader_score', 'neg', 'neu', 'pos', 'compound',
       'vader_category', 'polarity', 'subjectivity', 'emotional_score'],
      dtype='str')

In [45]:
prefix = "sentim_"

for col in psalmSentiment.columns: 
    psalmSentiment.rename(columns={col: prefix + col}, inplace=True)

In [46]:
# to beware clipped for final curation 
psalmSentiment.iloc[:, 3:].head()

,sentim_text,sentim_psalm_num,sentim_verse,sentim_cleaned_verse,sentim_vader_score,sentim_neg,sentim_neu,sentim_pos,sentim_compound,sentim_vader_category,sentim_polarity,sentim_subjectivity,sentim_emotional_score
0,Bible,1,Blessed is the man Who walks not in the counse...,blessed man walk counsel ungodly stand way sin...,"{'neg': 0.015, 'neu': 0.92, 'pos': 0.064, 'com...",0.015,0.920,0.064,0.7783,Positive,0.000000,0.000000,0.000000
1,Bible,2,Why do the nations rage And the people meditat...,nation rage people meditate vain thing king ea...,"{'neg': 0.12, 'neu': 0.787, 'pos': 0.093, 'com...",0.120,0.787,0.093,-0.6486,Negative,-0.153333,0.400000,-0.061333
2,Bible,3,A psalm by David when he fled from the face of...,psalm david fled face son absalom olord afflic...,"{'neg': 0.089, 'neu': 0.786, 'pos': 0.126, 'co...",0.089,0.786,0.126,0.8020,Positive,0.048889,0.437778,0.021402
3,Bible,4,For the End in psalms an ode by David You hear...,end psalm ode david heard icalled god righteou...,"{'neg': 0.092, 'neu': 0.748, 'pos': 0.159, 'co...",0.092,0.748,0.159,0.8919,Positive,0.178571,0.600000,0.107143
4,Bible,5,For the End concerning the inheritance a psalm...,end concerning inheritance psalm david give ea...,"{'neg': 0.13, 'neu': 0.712, 'pos': 0.157, 'com...",0.130,0.712,0.157,0.7774,Positive,0.075000,0.593750,0.044531

---
## Other Data

In [47]:
psalmsData = pd.read_csv("../data/psalms_with_data.csv")
psalmsData.head()

,Unnamed: 0,tradition,text,psalm_num,verse,fk_score,gf_score,smog_score,word_count,avg_word_len,syllable_count,avg_syllables_per_word,polysyllable_count,num_sentences,avg_words_sent,Psalm,kathisma_num,bertTopic
0,0,Orthodox,Bible,1,Blessed is the man Who walks not in the counse...,7.561153,11.272682,9.725611,133.0,3.962406,163,1.225564,8,6,22.166667,1.0,1.0,0
1,1,Orthodox,Bible,2,Why do the nations rage And the people meditat...,5.832270,8.643384,8.841846,199.0,4.190955,255,1.281407,12,12,16.583333,2.0,1.0,3
2,2,Orthodox,Bible,3,A psalm by David when he fled from the face of...,6.009667,9.100000,8.472885,150.0,3.766667,183,1.220000,7,8,18.750000,3.0,1.0,1
3,3,Orthodox,Bible,4,For the End in psalms an ode by David You hear...,6.264470,9.219697,7.168622,165.0,3.806061,189,1.145455,4,8,20.625000,4.0,1.0,1
4,4,Orthodox,Bible,5,For the End concerning the inheritance a psalm...,7.251237,10.524731,9.299571,248.0,4.096774,309,1.245968,14,12,20.666667,5.0,1.0,1

In [48]:
psalmsData.columns

Index(['Unnamed: 0', 'tradition', 'text', 'psalm_num', 'verse', 'fk_score',
       'gf_score', 'smog_score', 'word_count', 'avg_word_len',
       'syllable_count', 'avg_syllables_per_word', 'polysyllable_count',
       'num_sentences', 'avg_words_sent', 'Psalm', 'kathisma_num',
       'bertTopic'],
      dtype='str')

---

## Curating the Data

In [49]:
psalmSentiment['sentim_psalm_num']

0        1
1        2
2        3
3        4
4        5
      ...
296    146
297    147
298    148
299    149
300    150
Name: sentim_psalm_num, Length: 301, dtype: int64

In [50]:
psalmsData['psalm_num']

0        1
1        2
2        3
3        4
4        5
      ...
296    146
297    147
298    148
299    149
300    150
Name: psalm_num, Length: 301, dtype: int64

In [51]:
cols_to_add = [
    'fk_score',
    'gf_score',
    'smog_score',
    'word_count',
    'avg_word_len',
    'syllable_count',
    'avg_syllables_per_word',
    'polysyllable_count',
    'num_sentences',
    'avg_words_sent',
    'Psalm',
    'kathisma_num',
    'bertTopic'
]

psalmSentiment = psalmSentiment.merge(
    psalmsData[['psalm_num', 'verse'] + cols_to_add],
    left_on=['sentim_psalm_num'],
    right_on=['psalm_num'],
    how='left'
)

In [52]:
psalmSentiment.columns

Index(['sentim_Unnamed: 0.1', 'sentim_Unnamed: 0', 'sentim_tradition',
       'sentim_text', 'sentim_psalm_num', 'sentim_verse',
       'sentim_cleaned_verse', 'sentim_vader_score', 'sentim_neg',
       'sentim_neu', 'sentim_pos', 'sentim_compound', 'sentim_vader_category',
       'sentim_polarity', 'sentim_subjectivity', 'sentim_emotional_score',
       'psalm_num', 'verse', 'fk_score', 'gf_score', 'smog_score',
       'word_count', 'avg_word_len', 'syllable_count',
       'avg_syllables_per_word', 'polysyllable_count', 'num_sentences',
       'avg_words_sent', 'Psalm', 'kathisma_num', 'bertTopic'],
      dtype='str')

In [53]:
# Remove duplicate columns regardless of column name
psalms = psalmSentiment.loc[:, ~psalmSentiment.T.duplicated()]

print(psalms.columns)

Index(['sentim_Unnamed: 0.1', 'sentim_tradition', 'sentim_text',
       'sentim_psalm_num', 'sentim_verse', 'sentim_cleaned_verse',
       'sentim_vader_score', 'sentim_neg', 'sentim_neu', 'sentim_pos',
       'sentim_compound', 'sentim_vader_category', 'sentim_polarity',
       'sentim_subjectivity', 'sentim_emotional_score', 'verse', 'fk_score',
       'gf_score', 'smog_score', 'word_count', 'avg_word_len',
       'syllable_count', 'avg_syllables_per_word', 'polysyllable_count',
       'num_sentences', 'avg_words_sent', 'Psalm', 'kathisma_num',
       'bertTopic'],
      dtype='str')

In [54]:
psalms.drop_duplicates()
psalms.drop(columns=['sentim_verse'], inplace=True)

In [55]:
# cleaning up column names
psalms.columns = psalms.columns.str.replace('sentim_', '', regex=True)
psalms.head()

,Unnamed: 0.1,tradition,text,psalm_num,cleaned_verse,vader_score,neg,neu,pos,compound,...,word_count,avg_word_len,syllable_count,avg_syllables_per_word,polysyllable_count,num_sentences,avg_words_sent,Psalm,kathisma_num,bertTopic
0,0,Orthodox,Bible,1,blessed man walk counsel ungodly stand way sin...,"{'neg': 0.015, 'neu': 0.92, 'pos': 0.064, 'com...",0.015,0.920,0.064,0.7783,...,133.0,3.962406,163,1.225564,8,6,22.166667,1.0,1.0,0
1,0,Orthodox,Bible,1,blessed man walk counsel ungodly stand way sin...,"{'neg': 0.015, 'neu': 0.92, 'pos': 0.064, 'com...",0.015,0.920,0.064,0.7783,...,141.0,4.085106,173,1.226950,7,6,23.500000,1.0,1.0,0
2,1,Orthodox,Bible,2,nation rage people meditate vain thing king ea...,"{'neg': 0.12, 'neu': 0.787, 'pos': 0.093, 'com...",0.120,0.787,0.093,-0.6486,...,199.0,4.190955,255,1.281407,12,12,16.583333,2.0,1.0,3
3,1,Orthodox,Bible,2,nation rage people meditate vain thing king ea...,"{'neg': 0.12, 'neu': 0.787, 'pos': 0.093, 'com...",0.120,0.787,0.093,-0.6486,...,213.0,4.361502,272,1.276995,15,13,16.384615,2.0,1.0,3
4,2,Orthodox,Bible,3,psalm david fled face son absalom olord afflic...,"{'neg': 0.089, 'neu': 0.786, 'pos': 0.126, 'co...",0.089,0.786,0.126,0.8020,...,150.0,3.766667,183,1.220000,7,8,18.750000,3.0,1.0,1

In [56]:
psalms.drop(columns=['Psalm', 'vader_score'], inplace=True)

psalms.head()

,Unnamed: 0.1,tradition,text,psalm_num,cleaned_verse,neg,neu,pos,compound,vader_category,...,smog_score,word_count,avg_word_len,syllable_count,avg_syllables_per_word,polysyllable_count,num_sentences,avg_words_sent,kathisma_num,bertTopic
0,0,Orthodox,Bible,1,blessed man walk counsel ungodly stand way sin...,0.015,0.920,0.064,0.7783,Positive,...,9.725611,133.0,3.962406,163,1.225564,8,6,22.166667,1.0,0
1,0,Orthodox,Bible,1,blessed man walk counsel ungodly stand way sin...,0.015,0.920,0.064,0.7783,Positive,...,9.299571,141.0,4.085106,173,1.226950,7,6,23.500000,1.0,0
2,1,Orthodox,Bible,2,nation rage people meditate vain thing king ea...,0.120,0.787,0.093,-0.6486,Negative,...,8.841846,199.0,4.190955,255,1.281407,12,12,16.583333,1.0,3
3,1,Orthodox,Bible,2,nation rage people meditate vain thing king ea...,0.120,0.787,0.093,-0.6486,Negative,...,9.265574,213.0,4.361502,272,1.276995,15,13,16.384615,1.0,3
4,2,Orthodox,Bible,3,psalm david fled face son absalom olord afflic...,0.089,0.786,0.126,0.8020,Positive,...,8.472885,150.0,3.766667,183,1.220000,7,8,18.750000,1.0,1

In [57]:
psalms = pd.get_dummies(psalms, columns=['text'], drop_first=True, dtype=int)
psalms = pd.get_dummies(psalms, columns=['vader_category'], drop_first=False, dtype=int)

In [58]:
psalms.head()

,Unnamed: 0.1,tradition,psalm_num,cleaned_verse,neg,neu,pos,compound,polarity,subjectivity,...,avg_syllables_per_word,polysyllable_count,num_sentences,avg_words_sent,kathisma_num,bertTopic,text_Psalter,vader_category_Negative,vader_category_Neutral,vader_category_Positive
0,0,Orthodox,1,blessed man walk counsel ungodly stand way sin...,0.015,0.920,0.064,0.7783,0.000000,0.000000,...,1.225564,8,6,22.166667,1.0,0,0,0,0,1
1,0,Orthodox,1,blessed man walk counsel ungodly stand way sin...,0.015,0.920,0.064,0.7783,0.000000,0.000000,...,1.226950,7,6,23.500000,1.0,0,0,0,0,1
2,1,Orthodox,2,nation rage people meditate vain thing king ea...,0.120,0.787,0.093,-0.6486,-0.153333,0.400000,...,1.281407,12,12,16.583333,1.0,3,0,1,0,0
3,1,Orthodox,2,nation rage people meditate vain thing king ea...,0.120,0.787,0.093,-0.6486,-0.153333,0.400000,...,1.276995,15,13,16.384615,1.0,3,0,1,0,0
4,2,Orthodox,3,psalm david fled face son absalom olord afflic...,0.089,0.786,0.126,0.8020,0.048889,0.437778,...,1.220000,7,8,18.750000,1.0,1,0,0,0,1

In [68]:
psalms = psalms[['text_Psalter', 'psalm_num', 'verse', 'neg', 'neu', 'pos', 'compound', 'polarity', 'subjectivity', 
        'emotional_score', 'fk_score', 'gf_score', 'smog_score', 'word_count', 
        'avg_word_len', 'syllable_count', 'avg_syllables_per_word', 'polysyllable_count', 
        'num_sentences', 'avg_words_sent', 'kathisma_num', 'bertTopic', 
        'vader_category_Negative', 'vader_category_Neutral', 'vader_category_Positive']]

In [73]:
psalms.drop_duplicates(subset=['text_Psalter', 'psalm_num'], inplace=True)
psalms

,text_Psalter,psalm_num,verse,neg,neu,pos,compound,polarity,subjectivity,emotional_score,...,syllable_count,avg_syllables_per_word,polysyllable_count,num_sentences,avg_words_sent,kathisma_num,bertTopic,vader_category_Negative,vader_category_Neutral,vader_category_Positive
0,0,1,Blessed is the man Who walks not in the counse...,0.015,0.920,0.064,0.7783,0.000000,0.000000,0.000000,...,163,1.225564,8,6,22.166667,1.0,0,0,0,1
2,0,2,Why do the nations rage And the people meditat...,0.120,0.787,0.093,-0.6486,-0.153333,0.400000,-0.061333,...,255,1.281407,12,12,16.583333,1.0,3,1,0,0
4,0,3,A psalm by David when he fled from the face of...,0.089,0.786,0.126,0.8020,0.048889,0.437778,0.021402,...,183,1.220000,7,8,18.750000,1.0,1,0,0,1
6,0,4,For the End in psalms an ode by David You hear...,0.092,0.748,0.159,0.8919,0.178571,0.600000,0.107143,...,189,1.145455,4,8,20.625000,1.0,1,0,0,1
8,0,5,For the End concerning the inheritance a psalm...,0.130,0.712,0.157,0.7774,0.075000,0.593750,0.044531,...,309,1.245968,14,12,20.666667,1.0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
591,1,146,Alleluia of Aggeus and Zacharias Praise the Lo...,0.095,0.765,0.141,0.8417,0.157407,0.481481,0.075789,...,232,1.260870,10,11,16.727273,20.0,2,0,0,1
593,1,147,Alleluia of Aggeus and Zacharias Praise the Lo...,0.000,0.794,0.206,0.9808,-0.200000,0.650000,-0.130000,...,156,1.300000,4,9,13.333333,20.0,-1,0,0,1
595,1,148,Alleluia of Aggeus and Zacharias Praise the Lo...,0.018,0.749,0.233,0.9946,0.116667,0.316667,0.036944,...,258,1.277228,10,14,14.428571,20.0,2,0,0,1
597,1,149,Let Israel be glad in Him who made him And let...,0.017,0.759,0.224,0.9870,0.265455,0.664848,0.176487,...,177,1.282609,6,9,15.333333,20.0,2,0,0,1
599,1,150,Praise Him for His mighty acts Praise Him acco...,0.000,0.588,0.412,0.9930,0.400000,0.650000,0.260000,...,95,1.283784,6,6,12.333333,20.0,2,0,0,1

In [74]:
psalms.to_csv("offical_psalms_data.csv")