In [6]:
# %pip install --force-reinstall "numpy==1.26.4" "pandas>=2.1,<3"

In [3]:
import pandas as pd
import numpy as np

/opt/conda/lib/python3.11/site-packages/pandas/core/arrays/masked.py:61: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

# Pulling the separate data

In [35]:
import os 

print(os.getcwd())
os.chdir("../data/")
print(os.getcwd())


print("\nData to be curated:")
os.listdir()

/opt/notebooks/psalms-text-comparison/data
/opt/notebooks/psalms-text-comparison/data

Data to be curated:

['cleaned_psalm_verses.csv',
 'grouped_psalm.csv',
 'psalms_with_bertTopic.csv',
 'psalms_with_data.csv',
 'psalms_with_sentiment.csv',
 'psalms_with_data_2.csv']

---
## Sentiment Data

In [59]:
psalmSentiment = pd.read_csv("../data/psalms_with_sentiment.csv")
psalmSentiment.head()

,Unnamed: 0.1,Unnamed: 0,tradition,text,psalm_num,verse,cleaned_verse,vader_score,neg,neu,pos,compound,vader_category,polarity,subjectivity,emotional_score
0,0,0,Orthodox,Bible,1,Blessed is the man Who walks not in the counse...,blessed man walk counsel ungodly stand way sin...,"{'neg': 0.015, 'neu': 0.92, 'pos': 0.064, 'com...",0.015,0.920,0.064,0.7783,Positive,0.000000,0.000000,0.000000
1,1,1,Orthodox,Bible,2,Why do the nations rage And the people meditat...,nation rage people meditate vain thing king ea...,"{'neg': 0.12, 'neu': 0.787, 'pos': 0.093, 'com...",0.120,0.787,0.093,-0.6486,Negative,-0.153333,0.400000,-0.061333
2,2,2,Orthodox,Bible,3,A psalm by David when he fled from the face of...,psalm david fled face son absalom olord afflic...,"{'neg': 0.089, 'neu': 0.786, 'pos': 0.126, 'co...",0.089,0.786,0.126,0.8020,Positive,0.048889,0.437778,0.021402
3,3,3,Orthodox,Bible,4,For the End in psalms an ode by David You hear...,end psalm ode david heard icalled god righteou...,"{'neg': 0.092, 'neu': 0.748, 'pos': 0.159, 'co...",0.092,0.748,0.159,0.8919,Positive,0.178571,0.600000,0.107143
4,4,4,Orthodox,Bible,5,For the End concerning the inheritance a psalm...,end concerning inheritance psalm david give ea...,"{'neg': 0.13, 'neu': 0.712, 'pos': 0.157, 'com...",0.130,0.712,0.157,0.7774,Positive,0.075000,0.593750,0.044531

In [60]:
psalmSentiment.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'tradition', 'text', 'psalm_num', 'verse',
       'cleaned_verse', 'vader_score', 'neg', 'neu', 'pos', 'compound',
       'vader_category', 'polarity', 'subjectivity', 'emotional_score'],
      dtype='object')

In [61]:
prefix = "sentim_"

for col in psalmSentiment.columns: 
    psalmSentiment.rename(columns={col: prefix + col}, inplace=True)

In [62]:
# to beware clipped for final curation 
psalmSentiment.iloc[:, 3:].head()

,sentim_text,sentim_psalm_num,sentim_verse,sentim_cleaned_verse,sentim_vader_score,sentim_neg,sentim_neu,sentim_pos,sentim_compound,sentim_vader_category,sentim_polarity,sentim_subjectivity,sentim_emotional_score
0,Bible,1,Blessed is the man Who walks not in the counse...,blessed man walk counsel ungodly stand way sin...,"{'neg': 0.015, 'neu': 0.92, 'pos': 0.064, 'com...",0.015,0.920,0.064,0.7783,Positive,0.000000,0.000000,0.000000
1,Bible,2,Why do the nations rage And the people meditat...,nation rage people meditate vain thing king ea...,"{'neg': 0.12, 'neu': 0.787, 'pos': 0.093, 'com...",0.120,0.787,0.093,-0.6486,Negative,-0.153333,0.400000,-0.061333
2,Bible,3,A psalm by David when he fled from the face of...,psalm david fled face son absalom olord afflic...,"{'neg': 0.089, 'neu': 0.786, 'pos': 0.126, 'co...",0.089,0.786,0.126,0.8020,Positive,0.048889,0.437778,0.021402
3,Bible,4,For the End in psalms an ode by David You hear...,end psalm ode david heard icalled god righteou...,"{'neg': 0.092, 'neu': 0.748, 'pos': 0.159, 'co...",0.092,0.748,0.159,0.8919,Positive,0.178571,0.600000,0.107143
4,Bible,5,For the End concerning the inheritance a psalm...,end concerning inheritance psalm david give ea...,"{'neg': 0.13, 'neu': 0.712, 'pos': 0.157, 'com...",0.130,0.712,0.157,0.7774,Positive,0.075000,0.593750,0.044531

---
## Other Data

In [63]:
psalmsData = pd.read_csv("../data/psalms_with_data.csv")
psalmsData.head()

,Unnamed: 0,tradition,text,psalm_num,verse,fk_score,gf_score,smog_score,word_count,avg_word_len,syllable_count,avg_syllables_per_word,polysyllable_count,num_sentences,avg_words_sent,Psalm,kathisma_num,bertTopic
0,0,Orthodox,Bible,1,Blessed is the man Who walks not in the counse...,7.561153,11.272682,9.725611,133.0,3.962406,163,1.225564,8,6,22.166667,1.0,1.0,0
1,1,Orthodox,Bible,2,Why do the nations rage And the people meditat...,5.832270,8.643384,8.841846,199.0,4.190955,255,1.281407,12,12,16.583333,2.0,1.0,3
2,2,Orthodox,Bible,3,A psalm by David when he fled from the face of...,6.009667,9.100000,8.472885,150.0,3.766667,183,1.220000,7,8,18.750000,3.0,1.0,1
3,3,Orthodox,Bible,4,For the End in psalms an ode by David You hear...,6.264470,9.219697,7.168622,165.0,3.806061,189,1.145455,4,8,20.625000,4.0,1.0,1
4,4,Orthodox,Bible,5,For the End concerning the inheritance a psalm...,7.251237,10.524731,9.299571,248.0,4.096774,309,1.245968,14,12,20.666667,5.0,1.0,1

In [64]:
psalmsData.columns

Index(['Unnamed: 0', 'tradition', 'text', 'psalm_num', 'verse', 'fk_score',
       'gf_score', 'smog_score', 'word_count', 'avg_word_len',
       'syllable_count', 'avg_syllables_per_word', 'polysyllable_count',
       'num_sentences', 'avg_words_sent', 'Psalm', 'kathisma_num',
       'bertTopic'],
      dtype='object')

---

## Curating the Data

In [70]:
psalmSentiment['sentim_psalm_num']

0        1
1        2
2        3
3        4
4        5
      ...
296    146
297    147
298    148
299    149
300    150
Name: sentim_psalm_num, Length: 301, dtype: int64

In [56]:
psalmsData['psalm_num']

0        1
1        2
2        3
3        4
4        5
      ...
296    146
297    147
298    148
299    149
300    150
Name: psalm_num, Length: 301, dtype: int64

In [71]:
cols_to_add = [
    'fk_score',
    'gf_score',
    'smog_score',
    'word_count',
    'avg_word_len',
    'syllable_count',
    'avg_syllables_per_word',
    'polysyllable_count',
    'num_sentences',
    'avg_words_sent',
    'Psalm',
    'kathisma_num',
    'bertTopic'
]

psalmSentiment = psalmSentiment.merge(
    psalmsData[['psalm_num', 'verse'] + cols_to_add],
    left_on=['sentim_psalm_num'],
    right_on=['psalm_num'],
    how='left'
)

In [72]:
psalmSentiment

,sentim_Unnamed: 0.1,sentim_Unnamed: 0,sentim_tradition,sentim_text,sentim_psalm_num,sentim_verse,sentim_cleaned_verse,sentim_vader_score,sentim_neg,sentim_neu,...,word_count_y,avg_word_len_y,syllable_count_y,avg_syllables_per_word_y,polysyllable_count_y,num_sentences_y,avg_words_sent_y,Psalm_y,kathisma_num_y,bertTopic_y
0,0,0,Orthodox,Bible,1,Blessed is the man Who walks not in the counse...,blessed man walk counsel ungodly stand way sin...,"{'neg': 0.015, 'neu': 0.92, 'pos': 0.064, 'com...",0.015,0.920,...,133.0,3.962406,163,1.225564,8,6,22.166667,1.0,1.0,0
1,0,0,Orthodox,Bible,1,Blessed is the man Who walks not in the counse...,blessed man walk counsel ungodly stand way sin...,"{'neg': 0.015, 'neu': 0.92, 'pos': 0.064, 'com...",0.015,0.920,...,141.0,4.085106,173,1.226950,7,6,23.500000,1.0,1.0,0
2,1,1,Orthodox,Bible,2,Why do the nations rage And the people meditat...,nation rage people meditate vain thing king ea...,"{'neg': 0.12, 'neu': 0.787, 'pos': 0.093, 'com...",0.120,0.787,...,199.0,4.190955,255,1.281407,12,12,16.583333,2.0,1.0,3
3,1,1,Orthodox,Bible,2,Why do the nations rage And the people meditat...,nation rage people meditate vain thing king ea...,"{'neg': 0.12, 'neu': 0.787, 'pos': 0.093, 'com...",0.120,0.787,...,213.0,4.361502,272,1.276995,15,13,16.384615,2.0,1.0,3
4,2,2,Orthodox,Bible,3,A psalm by David when he fled from the face of...,psalm david fled face son absalom olord afflic...,"{'neg': 0.089, 'neu': 0.786, 'pos': 0.126, 'co...",0.089,0.786,...,150.0,3.766667,183,1.220000,7,8,18.750000,3.0,1.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
596,298,298,Orthodox,Psalter,148,Praise ye the Lord from the heavens; praise Hi...,praise ye lord heaven ; praise highest . prais...,"{'neg': 0.018, 'neu': 0.749, 'pos': 0.233, 'co...",0.018,0.749,...,207.0,4.318841,252,1.217391,6,16,12.937500,148.0,20.0,2
597,299,299,Orthodox,Psalter,149,"Sing unto the Lord a new song, His praise is i...","sing unto lord new song , praise congregation ...","{'neg': 0.017, 'neu': 0.759, 'pos': 0.224, 'co...",0.017,0.759,...,138.0,4.297101,177,1.282609,6,9,15.333333,149.0,20.0,2
598,299,299,Orthodox,Psalter,149,"Sing unto the Lord a new song, His praise is i...","sing unto lord new song , praise congregation ...","{'neg': 0.017, 'neu': 0.759, 'pos': 0.224, 'co...",0.017,0.759,...,137.0,4.430657,177,1.291971,6,9,15.222222,149.0,20.0,2
599,300,300,Orthodox,Psalter,150,Praise God in His holy ones; praise Him in the...,praise god holy one ; praise firmament power ...,"{'neg': 0.0, 'neu': 0.588, 'pos': 0.412, 'comp...",0.000,0.588,...,74.0,4.851351,95,1.283784,6,6,12.333333,150.0,20.0,2
600,300,300,Orthodox,Psalter,150,Praise God in His holy ones; praise Him in the...,praise god holy one ; praise firmament power ...,"{'neg': 0.0, 'neu': 0.588, 'pos': 0.412, 'comp...",0.000,0.588,...,78.0,4.628205,96,1.230769,4,6,13.000000,150.0,20.0,2

In [68]:
for

   sentim_psalm_num                                       sentim_verse
0                 1  Blessed is the man Who walks not in the counse...
1                 2  Why do the nations rage And the people meditat...
2                 3  A psalm by David when he fled from the face of...
3                 4  For the End in psalms an ode by David You hear...
4                 5  For the End concerning the inheritance a psalm...
sentim_psalm_num     int64
sentim_verse        object
dtype: object
   psalm_num                                              verse
0          1  Blessed is the man Who walks not in the counse...
1          2  Why do the nations rage And the people meditat...
2          3  A psalm by David when he fled from the face of...
3          4  For the End in psalms an ode by David You hear...
4          5  For the End concerning the inheritance a psalm...
psalm_num     int64
verse        object
dtype: object